# Generated by Django 5.1.1 on 2024-10-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bible', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('la ley', 'La Ley'), ('historicos', 'Historicos'), ('poeticos y de sabiduria', 'Poeticos Y De Sabiduria'), ('profetas mayores', 'Profetas Mayores'), ('profetas menores', 'Profetas Menores'), ('evangelicos', 'Evagenlicos'), ('cartas paulinas', 'Cartas Paulinas'), ('cartas generales', 'Cartas Generales'), ('historicos apostolicos', 'Historicos Apostolicos'), ('profeticos', 'Profeticos')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
