# Generated by Django 5.1.1 on 2024-10-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='name',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hijo', 'Hijo')], max_length=50),
        ),
    ]
